import gymnasium as gym
import numpy as np
import math

class EurekaRewardWrapper(gym.Wrapper):
    """
    Wrapper that calculates reward using THE FUNCTION CODED BY THE LLM
    1. Takes the code generated by the LLM
    2. Turns it into a Python function
    3. Forces the env to use the reward retuned by the LLM-generated reward function as the reward instead of real env reward
    """
    def __init__(self, env, reward_code_str):
        super().__init__(env)
        self.reward_code_str = reward_code_str # the raw text from the LLM

        # convert the code string into a function that can be used as reward function
        self.reward_function = self._compile_reward_code(reward_code_str)
        
        # Tracking to see how much reward the LLM is giving
        self.cumulative_intrinsic_reward = 0.0
        
    def _compile_reward_code(self, code_str):
        """
        Takes the string code generated by the LLM 
        Convert it into a callable python function
        """
        try:
            # Local scope for the function
            # Any variable LLM code defines ends up here
            local_scope = {}
            # Global scope with safe imports
            global_scope = {'np': np, 'math': math}
            
            # python code to execute a string defining a function
            exec(code_str, global_scope, local_scope)
            
            # check if llm correctly defined the function as 'compute_reward'
            if 'compute_reward' not in local_scope:
                # If LLM failed to name it correctly, try to find any callable
                for key, val in local_scope.items():
                    if callable(val):                        
                        return val
                raise ValueError("No function found in generated code")
            
            return local_scope['compute_reward']
            
        except Exception as e:
            print(f"[Eureka Wrapper Error] Compilation failed: {e}")
            return lambda env: 0.0  

    def step(self, action):
        # Take a step in the environment
        obs, reward, terminated, truncated, info = self.env.step(action)
        
        # Calculate Intrinsic Reward using the generated function
        # Pass self.unwrapped so the code can access .grid, .agent_pos, etc.
        
        # EXECUTE REWARD FUNCTION WITHOUT TRY/EXCEPT
        # We want this to raise an exception if the LLM code is buggy.
        # This allows the Search class to catch it and report the specific error text to the LLM.
        intrinsic_reward = self.reward_function(self.unwrapped)

        if intrinsic_reward is None: 
            # print("[Eureka Wrapper Warning] Reward function returned None -> defaulting intrinsic_reward: 0.0")
            # intrinsic_reward = 0.0            
            # This is a soft error, we can handle it gracefully or raise it. 
            # Usually better to raise so LLM fixes it.
            raise ValueError("Reward function returned None")

        #if intrisic reward returned by the LLM-generated reward function is out of bounds
        if intrinsic_reward < -0.1 or intrinsic_reward > 1.0:
            print(f"\n[WARNING Eureka Wrapper] Reward function returned out-of-bounds value {intrinsic_reward}\n")
            ### do not clip it is too invasive intrinsic_reward = max(-0.1, min(1.0, intrinsic_reward))
    
        # if you catch the error here the error will never reach the search function 
        # where you give feedback to the llm so it wont be able to improve the code
        # except Exception as e:
        #     print(f"[Eureka Wrapper Error] Reward function execution failed: {e}\n -> defaulting intrinsic_reward: 0.0")
        #     intrinsic_reward = 0.0
            
        #keep track 
        self.cumulative_intrinsic_reward += float(intrinsic_reward)
        
        #print(f"Eureka Wrapper Reward: {intrinsic_reward} / Env Reward: {reward}")
        if reward != 0.0:
            print(f"=> [Env Solved] EnvRwd: {reward} / LLMRwd: {intrinsic_reward} / TotalRwd: {(reward*5 + intrinsic_reward*5)}")
            total_reward = (reward*5) + float(intrinsic_reward*5)
            
        else:
            # i think is better to send to the pure rl alg ONLY THE INTRINSIC REWARD-> TO AVOID HAVING DIFFERNT SCALES
            #total_reward = float(intrinsic_reward)

            # send to the pure RL alg the INTRINSIC REWARD + env reward
            total_reward = reward + float(intrinsic_reward)
        
        return obs, total_reward, terminated, truncated, info

    def reset(self, **kwargs):
        self.cumulative_intrinsic_reward = 0.0
        return self.env.reset(**kwargs)